<?php
namespace Sohophp\SchemaOrg\Thing\Intangible;

use Sohophp\SchemaOrg\Thing\Intangible;

/**
* A service provided by an organization, e.g. delivery service, print services, etc.
* @see schema:Service
* @package Sohophp\SchemaOrg\Thing\Intangible
*/
class Service extends Intangible
{
   /**
        * An offer to provide this item&#x2014;for example, an offer to sell a product, rent the DVD of a movie, perform a service, or give away tickets to an event. Use [[businessFunction]] to indicate the kind of transaction offered, i.e. sell, lease, etc. This property can also be used to describe a [[Demand]]. While this property is listed as expected on a number of common types, it can be used in others. In that case, using a second type, such as Product or a subtype of Product, can clarify the nature of the offer.
      
        */
    protected $offers = null;

   /**
        * A pointer to another, functionally similar product (or multiple products).
        */
    protected $isSimilarTo = null;

   /**
        * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
        */
    protected $brand = null;

   /**
        * The geographic area where the service is provided.
        */
    protected $serviceArea = null;

   /**
        * Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
        */
    protected $providerMobility = null;

   /**
        * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
        */
    protected $serviceType = null;

   /**
        * A slogan or motto associated with the item.
        */
    protected $slogan = null;

   /**
        * An intended audience, i.e. a group for whom something was created.
        */
    protected $audience = null;

   /**
        * A pointer to another, somehow related product (or multiple products).
        */
    protected $isRelatedTo = null;

   /**
        * A review of the item.
        */
    protected $review = null;

   /**
        * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
        */
    protected $availableChannel = null;

   /**
        * The tangible thing generated by the service, e.g. a passport, permit, etc.
        */
    protected $produces = null;

   /**
        * An associated logo.
        */
    protected $logo = null;

   /**
        * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
        */
    protected $category = null;

   /**
        * Indicates an OfferCatalog listing for this Organization, Person, or Service.
        */
    protected $hasOfferCatalog = null;

   /**
        * The tangible thing generated by the service, e.g. a passport, permit, etc.
        */
    protected $serviceOutput = null;

   /**
        * An award won by or for this item.
        */
    protected $award = null;

   /**
        * The service provider, service operator, or service performer; the goods producer. Another party (a seller) may offer those services or goods on behalf of the provider. A provider may also serve as the seller.
        */
    protected $provider = null;

   /**
        * The overall rating, based on a collection of reviews or ratings, of the item.
        */
    protected $aggregateRating = null;

   /**
        * The hours during which this service or contact is available.
        */
    protected $hoursAvailable = null;

   /**
        * The audience eligible for this service.
        */
    protected $serviceAudience = null;

   /**
        * An entity that arranges for an exchange between a buyer and a seller.  In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.  If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
        */
    protected $broker = null;

   /**
        * The geographic area where a service or offered item is provided.
        */
    protected $areaServed = null;

   /**
        * Certification information about a product, organization, service, place, or person.
        */
    protected $hasCertification = null;

   /**
        * Human-readable terms of service documentation.
        */
    protected $termsOfService = null;


    /**
    * @param array|string $value
    * @return $this
    */
    public function setOffers($value)
    {
        $this->setProperty('offers', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getOffers()
    {
       return $this->getProperty('offers');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setIsSimilarTo($value)
    {
        $this->setProperty('isSimilarTo', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getIsSimilarTo()
    {
       return $this->getProperty('isSimilarTo');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setBrand($value)
    {
        $this->setProperty('brand', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getBrand()
    {
       return $this->getProperty('brand');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setServiceArea($value)
    {
        $this->setProperty('serviceArea', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getServiceArea()
    {
       return $this->getProperty('serviceArea');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setProviderMobility($value)
    {
        $this->setProperty('providerMobility', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getProviderMobility()
    {
       return $this->getProperty('providerMobility');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setServiceType($value)
    {
        $this->setProperty('serviceType', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getServiceType()
    {
       return $this->getProperty('serviceType');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setSlogan($value)
    {
        $this->setProperty('slogan', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getSlogan()
    {
       return $this->getProperty('slogan');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setAudience($value)
    {
        $this->setProperty('audience', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getAudience()
    {
       return $this->getProperty('audience');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setIsRelatedTo($value)
    {
        $this->setProperty('isRelatedTo', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getIsRelatedTo()
    {
       return $this->getProperty('isRelatedTo');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setReview($value)
    {
        $this->setProperty('review', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getReview()
    {
       return $this->getProperty('review');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setAvailableChannel($value)
    {
        $this->setProperty('availableChannel', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getAvailableChannel()
    {
       return $this->getProperty('availableChannel');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setProduces($value)
    {
        $this->setProperty('produces', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getProduces()
    {
       return $this->getProperty('produces');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setLogo($value)
    {
        $this->setProperty('logo', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getLogo()
    {
       return $this->getProperty('logo');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setCategory($value)
    {
        $this->setProperty('category', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getCategory()
    {
       return $this->getProperty('category');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setHasOfferCatalog($value)
    {
        $this->setProperty('hasOfferCatalog', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getHasOfferCatalog()
    {
       return $this->getProperty('hasOfferCatalog');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setServiceOutput($value)
    {
        $this->setProperty('serviceOutput', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getServiceOutput()
    {
       return $this->getProperty('serviceOutput');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setAward($value)
    {
        $this->setProperty('award', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getAward()
    {
       return $this->getProperty('award');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setProvider($value)
    {
        $this->setProperty('provider', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getProvider()
    {
       return $this->getProperty('provider');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setAggregateRating($value)
    {
        $this->setProperty('aggregateRating', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getAggregateRating()
    {
       return $this->getProperty('aggregateRating');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setHoursAvailable($value)
    {
        $this->setProperty('hoursAvailable', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getHoursAvailable()
    {
       return $this->getProperty('hoursAvailable');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setServiceAudience($value)
    {
        $this->setProperty('serviceAudience', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getServiceAudience()
    {
       return $this->getProperty('serviceAudience');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setBroker($value)
    {
        $this->setProperty('broker', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getBroker()
    {
       return $this->getProperty('broker');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setAreaServed($value)
    {
        $this->setProperty('areaServed', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getAreaServed()
    {
       return $this->getProperty('areaServed');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setHasCertification($value)
    {
        $this->setProperty('hasCertification', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getHasCertification()
    {
       return $this->getProperty('hasCertification');
    }

    /**
    * @param array|string $value
    * @return $this
    */
    public function setTermsOfService($value)
    {
        $this->setProperty('termsOfService', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getTermsOfService()
    {
       return $this->getProperty('termsOfService');
    }


}
