<?php
namespace Sohophp\SchemaOrg\Thing\CreativeWork\Article;

  use Sohophp\SchemaOrg\Thing\CreativeWork\Article;

/**
  * A Report generated by governmental or non-governmental organization.
  * @see schema:Report
* @package Sohophp\SchemaOrg\Thing\CreativeWork\Article
*/
class Report extends Article
{


  /**
      * The number or other unique designator assigned to a Report by the publishing
 * organization.
    * @param string|array $value
  * @return $this
  */
  public function reportNumber($value)
  {
  $this->setProperty('reportNumber', $value);
  return $this;
  }

  /**
  * @param string|array $value
  * @return $this
  */
  public function setReportNumber($value)
  {
  $this->setProperty('reportNumber', $value);
  return $this;
  }

  /**
  * @param string $value
  * @return $this
  */
  public function addReportNumber($value)
  {
  $current = $this->getProperty('reportNumber');
  if ($current === null) {
  $current = [];
  } elseif (!is_array($current)) {
  $current = [$current];
  }
  $current[] = $value;
  $this->setProperty('reportNumber', $current);
  return $this;
  }

  /**
  * @return string|array
  */
  public function getReportNumber()
  {
  return $this->getProperty('reportNumber');
  }


}
