<?php
namespace Sohophp\SchemaOrg\Thing\CreativeWork\Article;

use Sohophp\SchemaOrg\Thing\CreativeWork\Article;

/**
* A Report generated by governmental or non-governmental organization.
* @see schema:Report
* @package Sohophp\SchemaOrg\Thing\CreativeWork\Article
*/
class Report extends Article
{


    /**
        * The number or other unique designator assigned to a Report by the publishing
 * organization.
        * @param array|string|mixed $value
    * @return $this
    */
    public function reportNumber($value)
    {
        $this->setProperty('reportNumber', $value);
        return $this;
    }

    /**
    * @param array|string|mixed $value
    * @return $this
    */
    public function setReportNumber($value)
    {
        $this->setProperty('reportNumber', $value);
        return $this;
    }

    /**
    * @return string|array|mixed
    */
    public function getReportNumber()
    {
       return $this->getProperty('reportNumber');
    }


}
